### PR TITLE
Just some changes

### PR DESCRIPTION
**Pull request by S1SYPHOS**

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
So, will you consider merging this or should I close it?

**Comment by JoeeGrigg** [comment]
@S1SYPHOS Apologies for never getting back on this.

Do you still use it? If so are you interested in being a maintainer on this project?

I have no desire to maintain this however I am happy to add you to the project if you wish?

**Comment by S1SYPHOS** [comment]
I'm still using it for some projects, and would gladly maintain this project.

**Comment by luruke** [comment]
Hi there @S1SYPHOS and @JoeeGrigg .

With @thierrymichel we just released barba v2, and has css transitions support built-in:

https://barba.js.org/docs/v2/user/css.html

**Comment by JoeeGrigg** [comment]
@S1SYPHOS If you are still interested then you are more than welcome to take over this project? I will set this repo as deprecated and point everyone to your fork.

However, it is probably better to just update to Barba v2.

**Comment by S1SYPHOS** [comment]
I'm absolutely ecstatic to hear about Barba.js v2 (oh how I longed for this) - thank you, @luruke & @thierrymichel!

**Pull request closed without merging**
